# Docker Compose for Production
# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8080"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=webapp.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: unless-stopped